### ISSUE TITLE
Take seeds from a directory

### ISSUE THREAD

**Issue by CityOfLight77** [HGUfuzzing/php-fuzzer#13]
In readme, one can run php-fuzzer by supplying this command
`fuzzphp target-driver.php input.txt <source-dir>`

Instead of using one seed `input.txt` or whatever extensions, why not use seeds from a directory?
So the command will be `fuzzphp target-driver.php <corpus-directory> <source-dir>`

**Comment by HyeonseopJeong** [comment]
That's a good advice!
I was going to do it, but I forgot.
I'll let you know when I'm done with it.
